name: build-anki-cards
on:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: blablatdinov/anki-action@0.6.0
        with:
          path: anki-cards
      - name: Export anki cards to artifactory
        uses: actions/upload-artifact@v3
        with:
          name: cards.apkg
          path: ${{ github.workspace }}/cards.apkg
